### get all contacts
GET http://localhost:3000/contacts

### get one by id
Get http://localhost:3000/contacts/65ac0a7245eff24773ec0ab7

### Create a contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
    "firstName":"Joseph",
    "lastName":"Smith",
    "email":"jsmith@test.com",
    "favoriteColor":"Brown",
    "birthday":"06/19/2000"
}